spring.application.name=SkillSwap

server.port = 8082



# databse connection
spring.datasource.url=jdbc:mysql://localhost:3306/skillswap_app
spring.datasource.username=root
spring.datasource.password=prit123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


#for emial service

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=prithgol@gmail.com
spring.mail.password=xzyp kjpn tree ajln
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true